
version: '3'

services:
  web:
    build: .
    container_name: us_paper_cup_web
    restart: always
    ports:
      - "80:3000" # Expose internally, use Nginx/Reverse Proxy or direct if testing
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_Stripe_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DATABASE_URL=file:/app/prisma/dev.db # In-container DB path
    volumes:
      - ./prisma:/app/prisma # Persist DB and migrations
